In [2]:
import pandas as pd

In [3]:
data=pd.read_csv(r"C:\Users\swaya\OneDrive\Desktop\Python_pandas_projects\Sales-Data-Analysis.xlsx - Raw.csv")

In [9]:
data.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,NaN,10452,11/7/2022,Fries,3.49,573.07,Online,Gift Card,Tom Jackson,London
2,NaN,10453,11/7/2022,Beverages,2.95,745.76,Online,Gift Card,Pablo Perez,Madrid
3,NaN,10454,11/7/2022,Sides & Other,4.99,200.40,In-store,Gift Card,Joao Silva,Lisbon
4,NaN,10455,11/8/2022,Burgers,12.99,569.67,In-store,Credit Card,Walter Muller,Berlin

In [10]:
data.shape

(255, 10)

In [11]:
data.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9'],
      dtype='str')

In [12]:
data.drop(columns='Unnamed: 0',inplace=True)

In [13]:
data.head(2)

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,10452,11/7/2022,Fries,3.49,573.07,Online,Gift Card,Tom Jackson,London

In [14]:
data.loc[0]

Unnamed: 1          Order ID
Unnamed: 2              Date
Unnamed: 3           Product
Unnamed: 4             Price
Unnamed: 5          Quantity
Unnamed: 6     Purchase Type
Unnamed: 7    Payment Method
Unnamed: 8           Manager
Unnamed: 9              City
Name: 0, dtype: str

In [15]:
data.columns=data.loc[0]

In [16]:
data.head()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
0,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,10452,11/7/2022,Fries,3.49,573.07,Online,Gift Card,Tom Jackson,London
2,10453,11/7/2022,Beverages,2.95,745.76,Online,Gift Card,Pablo Perez,Madrid
3,10454,11/7/2022,Sides & Other,4.99,200.40,In-store,Gift Card,Joao Silva,Lisbon
4,10455,11/8/2022,Burgers,12.99,569.67,In-store,Credit Card,Walter Muller,Berlin

In [17]:
data.drop(0,inplace=True)

In [18]:
data.head()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,10452,11/7/2022,Fries,3.49,573.07,Online,Gift Card,Tom Jackson,London
2,10453,11/7/2022,Beverages,2.95,745.76,Online,Gift Card,Pablo Perez,Madrid
3,10454,11/7/2022,Sides & Other,4.99,200.40,In-store,Gift Card,Joao Silva,Lisbon
4,10455,11/8/2022,Burgers,12.99,569.67,In-store,Credit Card,Walter Muller,Berlin
5,10456,11/8/2022,Chicken Sandwiches,9.95,201.01,In-store,Credit Card,Walter Muller,Berlin

In [19]:
data.Manager

1        Tom      Jackson
2             Pablo Perez
3           Joao    Silva
4           Walter Muller
5           Walter Muller
              ...
250         Walter Muller
251         Walter Muller
252         Walter Muller
253         Walter Muller
254         Walter Muller
Name: Manager, Length: 254, dtype: str

In [20]:
data.Manager.unique()

<StringArray>
[  'Tom      Jackson', '       Pablo Perez',      'Joao    Silva',
      'Walter Muller',      'Remy    Monet',         'Remy Monet',
  '       Remy Monet',     'Remy     Monet',        'Pablo Perez',
      'Pablo   Perez',       'Pablo  Perez',     'Pablo    Perez',
         'Joao Silva',        'Tom Jackson']
Length: 14, dtype: str

In [21]:
data['Manager']=data['Manager'].str.strip().str.replace(r'\s+',' ',regex=True)

In [22]:
data.head()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,10452,11/7/2022,Fries,3.49,573.07,Online,Gift Card,Tom Jackson,London
2,10453,11/7/2022,Beverages,2.95,745.76,Online,Gift Card,Pablo Perez,Madrid
3,10454,11/7/2022,Sides & Other,4.99,200.40,In-store,Gift Card,Joao Silva,Lisbon
4,10455,11/8/2022,Burgers,12.99,569.67,In-store,Credit Card,Walter Muller,Berlin
5,10456,11/8/2022,Chicken Sandwiches,9.95,201.01,In-store,Credit Card,Walter Muller,Berlin

In [23]:
data.Manager.nunique()

5

In [24]:
data.describe()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
count,254,254,254,254,254,254,254,254,254
unique,254,53,5,7,29,3,3,5,5
top,10452,11/9/2022,Burgers,12.99,200.40,Online,Credit Card,Tom Jackson,London
freq,1,5,52,52,49,107,120,75,75

In [25]:
data.isnull().sum()

0
Order ID          0
Date              0
Product           0
Price             0
Quantity          0
Purchase Type     0
Payment Method    0
Manager           0
City              0
dtype: int64

In [26]:
data[data.duplicated()]

Empty DataFrame
Columns: [Order ID, Date, Product, Price, Quantity, Purchase Type, Payment Method, Manager, City]
Index: []

In [27]:
data.dtypes

0
Order ID          str
Date              str
Product           str
Price             str
Quantity          str
Purchase Type     str
Payment Method    str
Manager           str
City              str
dtype: object

In [30]:
data.Quantity=data.Quantity.astype(float)

In [31]:
data.columns

Index(['Order ID', 'Date', 'Product', 'Price', 'Quantity', 'Purchase Type',
       'Payment Method', 'Manager', 'City'],
      dtype='str', name=0)

In [32]:
data.dtypes

0
Order ID              str
Date                  str
Product               str
Price                 str
Quantity          float64
Purchase Type         str
Payment Method        str
Manager               str
City                  str
dtype: object

In [33]:
data.Quantity=data.Quantity.astype(int)

In [34]:
data.Quantity

1      573
2      745
3      200
4      569
5      201
      ...
250    200
251    754
252    281
253    630
254    677
Name: Quantity, Length: 254, dtype: int64

In [37]:
data['Order ID']=data['Order ID'].astype(int)

In [40]:
data['Order ID']

1      10452
2      10453
3      10454
4      10455
5      10456
       ...
250    10709
251    10710
252    10711
253    10712
254    10713
Name: Order ID, Length: 254, dtype: int64

In [41]:
data.Date=pd.to_datetime(data.Date)

In [42]:
data['Date']

1     2022-11-07
2     2022-11-07
3     2022-11-07
4     2022-11-08
5     2022-11-08
         ...
250   2022-12-28
251   2022-12-29
252   2022-12-29
253   2022-12-29
254   2022-12-29
Name: Date, Length: 254, dtype: datetime64[us]